export const songMoodsOptions = [
  "Acerbic",
  "Aggressive",
  "Agreeable",
  "Airy",
  "Ambitious",
  "Amiable/Good-Natured",
  "Angry",
  "Angst-Ridden",
  "Anguished/Distraught",
  "Angular",
  "Animated",
  "Anthemic",
  "Apocalyptic",
  "Arid",
  "Athletic",
  "Atmospheric",
  "Austere",
  "Autumnal",
  "Belligerent",
  "Benevolent",
  "Bitter",
  "Bittersweet",
  "Bleak",
  "Boisterous",
  "Bombastic",
  "Bouncy",
  "Brash",
  "Brassy",
  "Bravado",
  "Bright",
  "Brittle",
  "Brooding",
  "Calm/Peaceful",
  "Campy",
  "Capricious",
  "Carefree",
  "Cartoonish",
  "Cathartic",
  "Celebratory",
  "Cerebral",
  "Cheerful",
  "Child-like",
  "Circular",
  "Clinical",
  "Cold",
  "Comic",
  "Complex",
  "Concise",
  "Confessional",
  "Confident",
  "Confrontational",
  "Cosmopolitan",
  "Crunchy",
  "Cute",
  "Cynical/Sarcastic",
  "Dark",
  "Declamatory",
  "Defiant",
  "Delicate",
  "Demonic",
  "Desperate",
  "Detached",
  "Devotional",
  "Difficult",
  "Dignified/Noble",
  "Dissonant",
  "Dramatic",
  "Dreamy",
  "Driving",
  "Druggy",
  "Earnest",
  "Earthy",
  "Ebullient",
  "Eccentric",
  "Ecstatic",
  "Eerie",
  "Effervescent",
  "Elaborate",
  "Elegant",
  "Elegiac",
  "Energetic",
  "Enigmatic",
  "Epic",
  "Erotic",
  "Ethereal",
  "Euphoric",
  "Exciting",
  "Exotic",
  "Exploratory",
  "Explosive",
  "Extroverted",
  "Exuberant",
  "Fantastic/Fantasy-like",
  "Feral",
  "Feverish",
  "Fierce",
  "Fiery",
  "Flashy",
  "Flowing",
  "Fractured",
  "Freewheeling",
  "Fun",
  "Funereal",
  "Gentle",
  "Giddy",
  "Gleeful",
  "Gloomy",
  "Graceful",
  "Greasy",
  "Grim",
  "Gritty",
  "Gutsy",
  "Happy",
  "Harsh",
  "Heavy",
  "Hedonistic",
  "Heroic",
  "Hostile",
  "Humorous",
  "Hungry",
  "Hymn-like",
  "Hyper",
  "Hypnotic",
  "Improvisatory",
  "Indulgent",
  "Innocent",
  "Insular",
  "Intense",
  "Intimate",
  "Introspective",
  "Ironic",
  "Irreverent",
  "Jovial",
  "Joyous",
  "Kinetic",
  "Knotty",
  "Laid-Back/Mellow",
  "Languid",
  "Lazy",
  "Light",
  "Literate",
  "Lively",
  "Lonely",
  "Loose",
  "Lush",
  "Lyrical",
  "Macabre",
  "Magical",
  "Majestic",
  "Malevolent",
  "Manic",
  "Marching",
  "Martial",
  "Meandering",
  "Mechanical",
  "Meditative",
  "Melancholy",
  "Melodic",
  "Menacing",
  "Messy",
  "Mighty",
  "Monastic",
  "Monumental",
  "Motoric",
  "Mysterious",
  "Mystical",
  "Naive",
  "Narcotic",
  "Narrative",
  "Negative",
  "Nervous/Jittery",
  "Nihilistic",
  "Nocturnal",
  "Nostalgic",
  "Ominous",
  "Optimistic",
  "Opulent",
  "Organic",
  "Ornate",
  "Outraged",
  "Outrageous",
  "Paranoid",
  "Passionate",
  "Pastoral",
  "Patriotic",
  "Perky",
  "Philosophical",
  "Plain",
  "Plaintive",
  "Playful",
  "Poetic",
  "Poignant",
  "Positive",
  "Powerful",
  "Precious",
  "Provocative",
  "Pulsing",
  "Pure",
  "Quaint",
  "Quirky",
  "Radiant",
  "Rambunctious",
  "Ramshackle",
  "Raucous",
  "Reassuring/Consoling",
  "Rebellious",
  "Reckless",
  "Refined",
  "Reflective",
  "Regretful",
  "Relaxed",
  "Reserved",
  "Resolute",
  "Restrained",
  "Reverent",
  "Rhapsodic",
  "Rollicking",
  "Romantic",
  "Rousing",
  "Rowdy",
  "Rustic",
  "Sacred",
  "Sad",
  "Sarcastic",
  "Sardonic",
  "Satirical",
  "Savage",
  "Scary",
  "Scattered",
  "Searching",
  "Seductive",
  "Self-Conscious",
  "Sensual",
  "Sentimental",
  "Serious",
  "Severe",
  "Sexual",
  "Sexy",
  "Shimmering",
  "Silly",
  "Sleazy",
  "Slick",
  "Smooth",
  "Snide",
  "Soft/Quiet",
  "Somber",
  "Soothing",
  "Sophisticated",
  "Spacey",
  "Spacious",
  "Sparkling",
  "Sparse",
  "Spicy",
  "Spiritual",
  "Spontaneous",
  "Spooky",
  "Sprawling",
  "Sprightly",
  "Springlike",
  "Stately",
  "Street-Smart",
  "Striding",
  "Strong",
  "Stylish",
  "Suffocating",
  "Sugary",
  "Summery",
  "Sunny",
  "Suspenseful",
  "Swaggering",
  "Sweet",
  "Swinging",
  "Technical",
  "Tender",
  "Tense/Anxious",
  "Theatrical",
  "Thoughtful",
  "Threatening",
  "Thrilling",
  "Tight",
  "Tough",
  "Tragic",
  "Transparent/Translucent",
  "Trashy",
  "Trippy",
  "Triumphant",
  "Turbulent",
  "Uncompromising",
  "Understated",
  "Unsettling",
  "Uplifting",
  "Urgent",
  "Virile",
  "Visceral",
  "Volatile",
  "Vulgar",
  "Vulnerable",
  "Warm",
  "Weary",
  "Whimsical",
  "Wintry",
  "Wistful",
  "Witty",
  "Wry",
  "Yearning",
];
export const genrePrimaryOptions = [
  "Alternative",
  "Anime",
  "Blues",
  "Children's Music",
  "Classical",
  "Comedy",
  "Commercial",
  "Country",
  "Dance (EDM)",
  "Disney",
  "Easy Listening",
  "Electronic",
  "Fitness & Workout",
  "Folk Music",
  "Hip-Hop/Rap",
  "Indie Pop",
  "Industrial",
  "Inspirational - Christian & Gospel",
  "Instrumental",
  "Jazz",
  "K-Pop",
  "Karaoke",
  "Latin",
  "Metal",
  "New Age",
  "Opera",
  "Pop",
  "R&B",
  "Reggae",
  "Rock",
  "Singer/Songwriter",
  "Soul",
  "Soundtrack",
  "Spoken Word",
  "Vocal",
  "World",
];

export const genreSecondaryOptions = [
  "2-Step",
  "2-Tone",
  "8bit",
  "A cappella",
  "Acid Jazz",
  "Acid Rock",
  "Acoustic Blues",
  "Adult Alternative",
  "Adult Contemporary",
  "Adult-Oriented Rock",
  "Africa",
  "African Blues",
  "Afro Punk",
  "Afro-Cuban Jazz",
  "Aggrotech",
  "Alternative Country",
  "Alternative Folk",
  "Alternative Rap",
  "Alternative Rock",
  "Alternative Rock",
  "Alternativo & Rock Latino",
  "Ambient",
  "American Folk Revival",
  "American Traditional Rock",
  "Americana",
  "Anatolian Rock",
  "Anti-Folk",
  "Arab Pop",
  "Arena Rock",
  "Argentine Tango",
  "Art Punk",
  "Art Rock",
  "Asia",
  "Asian Underground",
  "Australia",
  "Australian Country",
  "Avant-Garde",
  "Avant-Garde Jazz",
  "Avantgarde Metal",
  "Bachata",
  "Background",
  "Baithak Gana",
  "Bakersfield Sound",
  "Baladas y Boleros",
  "Ballet",
  "Barbershop",
  "Baroque",
  "Bassline",
  "Bebop",
  "Big Band",
  "Black Metal",
  "Blue Note",
  "Bluegrass",
  "Blues Country",
  "Blues Rock",
  "Blues Shouter",
  "Blues-Rock",
  "Bolero",
  "Bop",
  "Bossa Nova",
  "Bounce",
  "Brazilian",
  "Breakbeat",
  "Breakcore",
  "Breakstep",
  "British Blues",
  "British Dance Band (Jazz)",
  "British Folk Revival",
  "British Invasion",
  "Britpop",
  "Britpunk",
  "Brostep",
  "Bubblegum Pop",
  "Cajun",
  "Cajun Fiddle Tunes",
  "Calypso",
  "Canadian Blues",
  "Cantata",
  "Cantique (sacred vocal)",
  "Cape Jazz",
  "Caribbean",
  "Carnatic (Karnataka Sanghetha)",
  "CCM",
  "Celtic",
  "Celtic Folk",
  "Chamber Jazz",
  "Chamber Music",
  "Chamber Pop",
  "Chanson",
  "Chant",
  "Chanukah",
  "Chap Hop",
  "Chicago Blues",
  "Chicano",
  "Chicha",
  "Chillstep",
  "Chillwave",
  "Chiptune",
  "Choral",
  "Christian & Gospel",
  "Christian Country",
  "Christian Hip Hop",
  "Christian Metal",
  "Christian Pop",
  "Christian Pop",
  "Christian Rap",
  "Christian Rock",
  "Christmas",
  "Christmas: Children’s",
  "Christmas: Classic",
  "Christmas: Classical",
  "Christmas: Comedy",
  "Christmas: Jazz",
  "Christmas: Modern",
  "Christmas: Pop",
  "Christmas: R&B",
  "Christmas: Religious",
  "Christmas: Rock",
  "Classic",
  "Classic Blues",
  "Classic Christian",
  "Classic Country",
  "Classic Female Blues",
  "Classical Crossover",
  "Classical Crossover",
  "Close Harmony",
  "Club / Club Dance",
  "Cock Rock",
  "Coldwave",
  "College Rock",
  "Concerto",
  "Concerto Grosso",
  "Conjunto",
  "Conjunto Progressive",
  "Conscious Hip Hop",
  "Contemporary Bluegrass",
  "Contemporary Blues",
  "Contemporary Celtic",
  "Contemporary Classical",
  "Contemporary Country",
  "Contemporary Folk",
  "Contemporary Gospel",
  "Contemporary Jazz",
  "Contemporary Latin",
  "Contemporary R&B",
  "Contemporary R&B",
  "Contemporary Singer/Songwriter",
  "Continental Jazz",
  "Cool Jazz",
  "Country Blues",
  "Country Gospel",
  "Country Pop",
  "Country Rap",
  "Country Rock",
  "Country Soul",
  "Country-Rap",
  "Coupé-décalé – Congo",
  "Cowboy / Western",
  "Cowpunk",
  "Criolla",
  "Crossover",
  "Crossover Jazz",
  "Crossover Thrash",
  "Crunk",
  "Crunkcore",
  "Crust Punk (thx Haug)",
  "Cumbia",
  "Cumbia Rap",
  "Cybergrind",
  "Dance Pop",
  "Dangdut",
  "Dansband",
  "Dark Blues",
  "Dark Electro",
  "Dark Jazz",
  "Death Industrial",
  "Death Metal",
  "Death Metal / Black Metal",
  "Deathcore",
  "Deep House",
  "Delta Blues",
  "Detroit Blues",
  "Dirty South",
  "Disco",
  "Dixieland",
  "Djent",
  "Doo Wop",
  "Doo-wop",
  "Doom Blues",
  "Doom Metal",
  "Downtempo",
  "Dream Pop",
  "Drinking Songs",
  "Drone",
  "Drum & Bass",
  "Drum’n’bass",
  "Dub",
  "Dubstep",
  "Early Jazz",
  "Early Music",
  "East Coast",
  "Easter",
  "Electric Blues",
  "Electro",
  "Electro House",
  "Electro Pop",
  "Electro Swing (Jazz)",
  "Electro-Industrial",
  "Electro-swing",
  "Electroacoustic",
  "Electronic Body Music",
  "Electronic Rock",
  "Electronica",
  "Electroswing",
  "Elevator",
  "Emo",
  "Enka",
  "Entechno",
  "Environmental",
  "Ethio-jazz",
  "Ethno-Jazz",
  "Eurodance",
  "European Free Jazz",
  "Europop",
  "Exercise",
  "Experimental Rock",
  "Expressionist",
  "Fado",
  "Filk Music",
  "Flamenco / Spanish Flamenco",
  "Folk Blues",
  "Folk Metal",
  "Folk Punk",
  "Folk-Rock",
  "Foreign Cinema",
  "France",
  "Franco-Country",
  "Freak Folk",
  "Free Funk (Avant-Garde / Funk Jazz)",
  "Free Jazz",
  "Freestyle Rap",
  "Funk",
  "Furniture",
  "Fusion",
  "Future Garage",
  "G-Funk",
  "Gangsta Rap",
  "Garage",
  "German Folk",
  "German Pop",
  "Glam Metal",
  "Glam Rock",
  "Glitch Hop",
  "Glitch Pop",
  "Golden Age",
  "Gospel",
  "Gospel Blues",
  "Goth / Gothic Rock",
  "Gothic Metal",
  "Gothic Metal",
  "Gregorian Chant",
  "Grime",
  "Grind Core",
  "Grindcore",
  "Groove Metal",
  "Grunge",
  "Grunk",
  "Gulf and Western",
  "Gypsy Jazz",
  "Hair Metal",
  "Halloween",
  "Hard Bop",
  "Hard Dance",
  "Hard Rock",
  "Hardcore",
  "Hardcore",
  "Hardcore Punk",
  "Hardcore Rap",
  "Hardstyle",
  "Harmonica Blues",
  "Hawaii",
  "Healing",
  "Heavy Metal",
  "Hellbilly Music",
  "Hi-Nrg",
  "Hi-NRG / Eurodance",
  "High Classical",
  "Hill Country Blues",
  "Hip Pop",
  "Hokum Blues",
  "Holiday: Other",
  "Honky Tonk",
  "Horrorcore",
  "House",
  "Huayno",
  "Hyphy",
  "IDM/Experimental",
  "Impressionist",
  "Indie Folk",
  "Indie Rock",
  "Indo Jazz",
  "Industrial",
  "Industrial Folk",
  "Industrial Hip Hop",
  "Industrial Metal",
  "Industrial Rock",
  "Instrumental Country",
  "Instrumental Hip Hop",
  "Iranian Pop",
  "J-Punk",
  "J-Rock",
  "J-Ska",
  "J-Synth",
  "Jackin House",
  "Jam Bands",
  "Jangle Pop",
  "Japan",
  "Jazz Blues",
  "Jazz Blues",
  "Jazz Rap",
  "Jazz Rock",
  "Jazz-Funk",
  "Jazz-Fusion",
  "Jingles",
  "Joropo",
  "Jump Blues",
  "Jungle",
  "Kansas City Blues",
  "Kansas City Jazz",
  "Kawaii Metal",
  "Kayokyoku",
  "Klezmer",
  "Laiko",
  "Latin Ballad",
  "Latin Jazz",
  "Latin Rap",
  "Levenslied",
  "Liquid Dub",
  "Lo-fi",
  "Louisiana Blues",
  "Louisiana Swamp Pop",
  "Lounge",
  "Love Song (Chanson)",
  "Lovers Rock",
  "Low Bap",
  "Lubbock Sound",
  "Lullabies",
  "Lyrical Hip Hop",
  "M-Base Jazz",
  "Mainstream Jazz",
  "Mambo (Cuba)",
  "March (Marching Band)",
  "Mariachi",
  "Mass Requiem",
  "Math Metal",
  "Math Rock",
  "Mathcore",
  "Mbalax – Senegal",
  "Medieval",
  "Meditation",
  "Memphis Blues",
  "Merengue Típico",
  "Merenrap",
  "Metal",
  "Metal Core",
  "Metalcore",
  "Mexican Pop",
  "Middle East",
  "Middle of the Road",
  "Midwest Hip Hop",
  "Minimalism",
  "Modal Jazz",
  "Modern Blues",
  "Modern Classical",
  "Modern Composition",
  "Modern Metal",
  "Modern Soul",
  "Motorpop",
  "Motown",
  "Motswako",
  "Movie Soundtrack",
  "Musicals",
  "Musique Concrète",
  "Nashville Sound",
  "Nature",
  "Neo-Bop",
  "Neo-Soul",
  "Neo-Swing",
  "Neoclassical Metal",
  "Neofolk",
  "Neotraditional Country",
  "Nerdcore",
  "Neue Deutsche Härte",
  "New Acoustic",
  "New Jack Swing",
  "New Mex",
  "New Orlean Blues",
  "New Romanticism",
  "New School Hip Hop",
  "New Wave",
  "New Wave Of British Heavy Metal",
  "Noise",
  "Noise Rock",
  "North America",
  "Northern Soul",
  "Novelty",
  "Nu Jazz",
  "Nu Metal",
  "Nuevo Flamenco",
  "NY Blues",
  "Ode",
  "Old School Rap",
  "Opera",
  "Oratorio",
  "Orchestral",
  "Orchestral Jazz",
  "Orchestral Pop",
  "Organum",
  "Original Score",
  "Outlaw Country",
  "Pagan Metal",
  "Parody Music",
  "Piano Blues",
  "Piedmont Blues",
  "Piphat – Thailand",
  "Pirate Metal",
  "Polka",
  "Pop Latino",
  "Pop Punk",
  "Pop Rap",
  "Pop/Rock",
  "Popera",
  "Portuguese Fado",
  "Post Hardcore",
  "Post Metal",
  "Post Punk",
  "Post Rock",
  "Post-Bop",
  "Post-Disco",
  "Power Metal",
  "Power Pop",
  "Praise & Worship",
  "Prog-Rock/Art Rock",
  "Progressive",
  "Progressive Folk",
  "Progressive Metal",
  "Progressive Metal",
  "Progressive Rock",
  "Psychedelic",
  "Psychedelic Folk",
  "Psychedelic Pop",
  "Psychedelic Soul",
  "Psychobilly / Punkabilly",
  "Punk",
  "Punk Blues",
  "Punk Jazz",
  "Punta",
  "Punta Rock",
  "Qawwali",
  "Quiet Storm",
  "Raggamuffin",
  "Ragtime",
  "Ragtime Blues",
  "Raíces",
  "Raison",
  "Ranchera",
  "Rap",
  "Rebetika",
  "Red Dirt",
  "Reggae Dancehall",
  "Reggae en Español",
  "Reggae Fusion",
  "Reggaeton",
  "Regional Mexicano",
  "Regstep",
  "Relaxation",
  "Renaissance",
  "Rhythm Blues",
  "Rock & Roll",
  "Rockabilly",
  "Romantic (early period)",
  "Romantic (later period)",
  "Roots Reggae",
  "Roots Rock",
  "Salsa y Tropical",
  "Schlager",
  "Sertanejo",
  "Shoegaze",
  "Sing-Along",
  "Singer/Songwriter",
  "Ska",
  "Ska Jazz",
  "Skiffle (also Folk)",
  "Sludge",
  "Smooth Jazz",
  "Soca",
  "Soft Rock",
  "Son",
  "Sonata",
  "Sophisti-Pop",
  "Soul",
  "Soul Blues",
  "Soul Jazz",
  "Soundtrack",
  "South / Southeast Asia",
  "South Africa",
  "South America",
  "Southern Gospel",
  "Southern Rock",
  "Southern Soul",
  "Space Age Pop",
  "Spazzcore",
  "Speed Metal",
  "Speedcore",
  "St. Louis Blues",
  "Stand-up Comedy",
  "Standards",
  "Steampunk",
  "Stoner Metal (duuuude)",
  "Stories",
  "Straight-Ahead Jazz",
  "String Quartet",
  "Sung Poetry",
  "Sunshine Pop",
  "Surf",
  "Surf Pop",
  "Swamp Blues",
  "Swing",
  "Swing Jazz",
  "Symphonic",
  "Symphonic Metal",
  "Symphony",
  "Synthpop",
  "Technical Death Metal",
  "Techno",
  "Techno-Folk",
  "Teen Pop",
  "Tejano",
  "Tex-Mex",
  "Tex-Mex / Tejano",
  "Texas Blues",
  "Texas County",
  "Thanksgiving",
  "Third Stream",
  "Thrash Metal",
  "Timba",
  "Time Lord Rock (Trock)",
  "Trad Jazz",
  "Traditional Bluegrass",
  "Traditional Celtic",
  "Traditional Country",
  "Traditional Folk",
  "Traditional Gospel",
  "Traditional Pop",
  "Traditional Pop Music",
  "Trance",
  "Trap",
  "Trave",
  "Trip Hop",
  "Trip-hop",
  "Truck-Driving Country",
  "Turkish Pop",
  "Turntablism",
  "TV Soundtrack",
  "TV Themes",
  "Twelve-tone",
  "Twoubadou",
  "UK Garage",
  "Underground Rap",
  "Urban Blues",
  "Urban Cowboy",
  "Vallenato",
  "Vandeville",
  "Vaporwave",
  "Vaudeville",
  "Viking Metal",
  "Vispop",
  "Vocal Jazz",
  "Vocal Pop",
  "Wedding Music",
  "West Coast Blues",
  "West Coast Jazz",
  "West Coast Rap",
  "Western Swing",
  "Witch House",
  "Wonky Pop",
  "Worldbeat",
  "Yacht Rock (soft rock)",
  "Yodel",
  "Zouk",
  "Zydeco",
];
export const subGenreOptions = [
  "4-Beat",
  "4×4",
  "Acid Breaks",
  "Acid House",
  "Acid Jazz",
  "Acid Techno",
  "Acid Trance",
  "Acid-House",
  "Acousmatic Music",
  "African Heavy Metal",
  "African Hip Hop",
  "Afro-Beat",
  "Afro-House",
  "Afro-Pop",
  "Alternative Dance",
  "Ambient Dub",
  "Ambient House",
  "Ambient Techno",
  "Anison",
  "Apala (or akpala)",
  "Austropop",
  "Axé",
  "Baggy",
  "Baila",
  "Baithak Gana",
  "Balearic Beat",
  "Balkan Pop",
  "Baltimore Club",
  "Bassline",
  "Benga",
  "Berlin School",
  "Bhangra",
  "Bhojpuri",
  "Big Beat",
  "Bikutsi",
  "Bitpop",
  "Bongo Flava",
  "Boogie",
  "Bossa Nova",
  "Bounce / Scouse House",
  "Bouncy House",
  "Bouncy Techno",
  "Brazilian Rock",
  "Breakbeat Hardcore",
  "Breakcore",
  "Brega",
  "Brick City Club",
  "Broken Beat",
  "Bubblegum Dance",
  "C-Pop",
  "Cantopop",
  "Cape Jazz",
  "Chicago Hip Hop",
  "Chicago House",
  "Chill Out",
  "Chillwave",
  "Chimurenga",
  "Choro",
  "Chutney",
  "Chutney Soca",
  "CityPop",
  "Classic Trance",
  "Compas",
  "Computer Music",
  "Coupé-Décalé",
  "Crunk",
  "Dance-pop",
  "Dance-Punk",
  "Dance-Rock",
  "Dancehall",
  "Dangdut",
  "Dark Ambient",
  "Dark Psy",
  "Dark Psytrance",
  "Dark Wave",
  "Darkcore",
  "Darkside Jungle",
  "Darkstep",
  "Deep House",
  "Detroit Hip Hop",
  "Detroit Techno",
  "Digital Hardcore",
  "Disco House",
  "Diva House",
  "Doomcore",
  "Dream House",
  "Dream Trance",
  "Drone Music",
  "Drumfunk",
  "Drumstep",
  "Dub",
  "Dub Music",
  "Dubstyle",
  "Dubtronica",
  "Dutch House",
  "Electro Backbeat",
  "Electro House",
  "Electro-Grime",
  "Electroacoustic Improvisation",
  "Electroclash",
  "Electronic Art Music",
  "Electronic Dance Music",
  "Electronicore",
  "Electropop",
  "Electropunk",
  "Enka",
  "Ethereal Wave",
  "Ethnic Electronica",
  "Eurobeat",
  "Fann At-Tanbura",
  "Field Recording",
  "Fijiri",
  "Filmi",
  "Florida Breaks",
  "Folktronica",
  "Forró",
  "Free Tekno",
  "Freestyle House",
  "Freestyle Music",
  "French House",
  "French Pop",
  "Frevo",
  "Fuji Music",
  "Full on",
  "Funk Carioca",
  "Funky House",
  "Futurepop",
  "Gabber",
  "Game Boy",
  "Genge",
  "Ghetto House",
  "Ghettotech",
  "Glitch",
  "Gnawa (hypnotic trance)",
  "Goa Trance",
  "Grime",
  "Happy Hardcore",
  "Hard Nrg",
  "Hard Trance",
  "Hardbag",
  "Hardcore Hip Hop",
  "Hardstep",
  "Hardstyle",
  "Highlife",
  "Hindustani",
  "Hip House",
  "Hiplife",
  "Hong Kong English Pop",
  "Horrorcore",
  "Hyponagogic",
  "Idm",
  "Illbient",
  "Indian Ghazal",
  "Indian Pop",
  "Indietronica",
  "Intelligent Drum and Bass",
  "Isicathamiya",
  "Isolationism",
  "Italo Dance",
  "Italo House",
  "J-Pop",
  "Japanese House",
  "Japanese Pop",
  "Japanoise",
  "Jit",
  "Jùjú",
  "Jump-Up",
  "Jumpstyle",
  "K-Pop",
  "Kapuka",
  "Kayōkyoku",
  "Khaliji",
  "Kizomba",
  "Korean Pop",
  "Kuduro",
  "Kwaito",
  "Kwela",
  "Laïkó",
  "Lambada",
  "Laptronica",
  "Latin House",
  "Latin Pop",
  "Lavani",
  "Lingala (Rumba Lingala / Congolese Rumba)",
  "Liquid Funk",
  "Live Coding",
  "Live Electronics",
  "Liwa",
  "Lowercase",
  "Luk Krung",
  "Luk Thung",
  "Madchester",
  "Mafioso Rap",
  "Makina",
  "Makossa",
  "Mallsoft",
  "Maloya",
  "Mambo",
  "Mandopop",
  "Manila Sound",
  "Maracatu",
  "Marrabenta",
  "Mbalax",
  "Mbaqanga",
  "Mbube",
  "Merengue",
  "Méringue",
  "Minimal",
  "Minimal House",
  "Minimal Techno",
  "Moombahton",
  "Morlam",
  "Morna",
  "Museve",
  "Música Popular Brasileira",
  "Música Sertaneja",
  "Nederpop",
  "Negro Spiritual",
  "Neurofunk",
  "New Beat",
  "New Jersey Hip Hop",
  "New Rave",
  "Nintendocore",
  "Nortec",
  "Nu Jazz",
  "Nu Skool Breaks",
  "Oldschool Jungle:",
  "Onkyokei",
  "Orchestral Uplifting",
  "Pagode",
  "Palm-Wine",
  "Pinoy Pop",
  "Pop Sunda",
  "Power Electronics",
  "Power Noise",
  "Prog. Trance",
  "Progressive Bluegrass",
  "Progressive Breaks",
  "Progressive Drum & Bass",
  "Progressive House",
  "Progressive House / Trance",
  "Progressive Techno",
  "Protovapor",
  "Psy-Trance",
  "Psybreaks",
  "Psyprog",
  "Ragga",
  "Ragga Jungle",
  "Raggacore",
  "Ragini",
  "Raï",
  "Rave Music",
  "Reactionary Bluegrass",
  "Reggae 110",
  "Reggae Bultrón",
  "Rocksteady",
  "Romantic Flow",
  "Russian Pop",
  "Sakara",
  "Samba",
  "Samba Rock",
  "Sambass",
  "Sawt",
  "Schranz",
  "Sega",
  "Seggae",
  "Semba",
  "Skweee",
  "Soukous",
  "Sound Art",
  "Soundscape Composition",
  "Space House",
  "Space Rock",
  "Spanish Reggae",
  "Speed Garage",
  "Speedcore",
  "St. Louis Hip Hop",
  "Suomisaundi",
  "Swing House",
  "Synthcore",
  "Synthpop",
  "Synthpunk",
  "T-Pop (Thai pop)",
  "Taarab",
  "Taiwanese Pop",
  "Tape Music",
  "Tech House",
  "Tech Trance",
  "Techno-Dnb",
  "Technopop",
  "Techstep",
  "Tecno Brega",
  "Terrorcore",
  "Thai Pop",
  "Toytown Techno",
  "Tribal House",
  "Trip Hop",
  "Tropical House",
  "Tropicalia",
  "Turbofolk",
  "Twin Cities Hip Hop",
  "UK Hard House",
  "Uk Hardcore",
  "Uplifting Trance",
  "US Garage",
  "Vaporhop",
  "Vaportrap",
  "Vektroid",
  "Video Game Music",
  "Vocal House",
  "Vocal Trance",
  "Yorkshire Bleeps and Bass",
  "Zouglou",
  "Zouk-Lambada",
];
export const musicKeys = [
  { key: "C major", id: "CMa" },
  { key: "D♭ major", id: "DflMa" },
  { key: "D major", id: "DMa" },
  { key: "E♭ major", id: "EflMa" },
  { key: "E major", id: "EMa" },
  { key: "F major", id: "FMa" },
  { key: "F# major", id: "FshMa" },
  { key: "G major", id: "GMa" },
  { key: "A♭ major", id: "AflMa" },
  { key: "A major", id: "AMa" },
  { key: "B♭ major", id: "BflMa" },
  { key: "B major", id: "BMa" },
  { key: "C minor", id: "CMi" },
  { key: "C# minor", id: "CshMi" },
  { key: "D minor", id: "DMi" },
  { key: "E♭ minor", id: "EflMi" },
  { key: "E minor", id: "EMi" },
  { key: "F minor", id: "FMi" },
  { key: "F# minor", id: "FshMi" },
  { key: "G minor", id: "GMi" },
  { key: "G# minor", id: "GshMi" },
  { key: "A minor", id: "AMi" },
  { key: "A♭ minor", id: "AflMi" },
  { key: "B♭ minor", id: "BflMi" },
  { key: "B minor", id: "BMi" },
];
